name: Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          disk-cache: true
          bazelisk-cache: true
          repository-cache: true
      - name: Run tests
        run: bazel
          --bazelrc=${{ github.workspace }}/.github/ci.bazelrc
          run
          --compilation_mode=opt --stamp
          //docs:publish_book
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/book # The folder the action should deploy.
